### ISSUE TITLE
Request: Please Support Latest ESR For uMatrix

### ISSUE THREAD

**Issue by 0pLuS0** [uBlockOrigin/uMatrix-issues#18]
Can you please support the latest Firefox ESR versions to work with the latest uMatrix...

THANKS

**Comment by uBlock-user** [comment]
Firefox-legacy support has been removed since months now, if that's what you mean.

**Comment by gorhill** [comment]
The latest Firefox ESR is Firefox 60 -- it should be compatible. If not, provide mode details as to what does not work, repro steps, etc.

**Comment by metadings** [comment]
Dear Mr Gorhill look, I did on Raspbian ARM AArch64:
-  sudo apt update && sudo apt install firefox-esr  # this is v52.9.0 (32-bit)

I about:config'ured `xpinstall.signatures.required`, but I can't install this, Firefox says 'uMatrix couldn't be installed, because it's not compatible with Firefox 52.9.0'...

**Comment by uBlock-user** [comment]
> but I can't install this, Firefox says 'uMatrix couldn't be installed, because it's not compatible with Firefox 52.9.0'

> The latest Firefox ESR is Firefox 60

get FF 60.

**Comment by gorhill** [comment]
You should seek help with the maintainers if GNU/Linux Raspbian Desktop, they should already ship with Firefox 60 ESR. From [here](https://www.raspberrypi.org/downloads/raspbian/) it seems they published a new release in April of this year, so surely the Firefox ESR package has been updated to 60.
