### ISSUE TITLE
treat third party scripts with sub resource integrity (sri) as 1st party [new feature]

### ISSUE THREAD

**Issue by rajeevn1** [uBlockOrigin/uMatrix-issues#181]
Please treat third party scripts with SRI (the 1st party is confirming the integrity) as 1st party script.

**Comment by gorhill** [comment]
That's not possible, the webRequest listener responsible for blocking network requests does not know about the DOM, where the `integrity` attribute is found.

**Comment by rajeevn1** [comment]
how about treating all scripts as 1st party, if the the page uses 'strict-dynamic' content security policy in script-src.

**Comment by gorhill** [comment]
I don't see the point of confusing users by treating 3rd parties as first party. That a specific server trust very much a specific 3rd party us irrelevant to me as a user, what is relevant is that the 3rd party is distinct from the 1st party. By your logic, a Google Analytics script would become first party just because the server took steps to guarantee the resource integrity. That is irrelevant to me as a user.

**Comment by uBlock-user** [comment]
The very definition of third-party resource is something that doesn't originate from the url that you're visiting, anything else is irrelevant.
