### ISSUE TITLE
Domain cell appears in green when blocking root document

### ISSUE THREAD

**Issue by rjkpa** [uBlockOrigin/uMatrix-issues#61]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Domain cell appears in green when blocking root document with type `doc`

### A specific URL where the issue occurs

`https://www.example.com/`

### Steps to Reproduce

1. Go to `https://www.example.com/`
2. Add `* example.com doc block` in My Rules and save it.
3. Refresh to enforce strick blocking and open the popup panel 

### Expected  result

![](https://i.gyazo.com/f4b22e1d1bf1eeccd5baf50d6bbf7018.png)

### Actual result

![](https://i.gyazo.com/34f60a1d7bed0aa0cfad5ae06a541a37.png)

### Your environment

* uMatrix version: 1.3.15.2
* Browser Name and version: Chrome/Firefox dev
* Operating System and version: Win X

**Comment by gorhill** [comment]
The `doc` cell is not visible in the matrix, and in any case, the cells `* example.com *`, `1st-party example.com *` and `example.com example.com *` never inherit from `* example.com doc`, it's the other way around.

**Comment by rjkpa** [comment]
The behavior is not consistent with `* example * block`, because they both do the same thing and that creates a discrepancy.

**Comment by gorhill** [comment]
> The behavior is not consistent with * example.com * block, because they both do the same thing

They do not do the same thing. `* example.com * block` block all resource types, and all decendant type cells (i.e. `* example.com image`, etc.) will inherit that rules. `* example.com doc block` blocks only root document, and is not inherited by other type cells. Hence why it's not reported in the matrix because it is pointless to do so, there is only one such cell in the whole matrix.

In very early development of uMatrix, I did try to get rid of the `doc` cell and instead just decide whether root document should be blocked using solely the `* example.com *` cell, but this broke everything: there are no whitelist rules in uMatrix, and without the `doc` type and the default rule `* * doc allow`, **all** sites would be blocked by default (not everybody necessarily agree with `* 1st-party * allow`/`* 1st-party frame allow` and anyone is free to remove these. So the `doc` type is there to ensure graylisted sites (which is all sites not listed in any hosts files) would be blocked by default.

> Was this mentioned anywhere in the wiki ?

Narrower cells inherit from broader cell, I keep repeating this throughout the wiki.

`* example.com doc` inherits from `* example.com *`, which inherits from `* com *`, which inherits from `* * *`.

**Comment by rjkpa** [comment]
> Narrower cells inherit from broader cells, I keep repeating this throughout the wiki.

I know that, I didn't think `doc` was narrower, hence my question. Anyways, the visual inconsistency created by this rule is the main problem for me and since that will remain, I will have to use `*` instead of doc. Thanks for answering in detail.
